-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.3.1
    hooks:
    -   id: pylint
        args:
        - --max-line-length=70
        - -d duplicate-code
        - --good-names=dx
