#!/usr/bin/env python3

"""

Given data on displacement, this script calculates derived quantities,
including
- velocity
- strain
- beat rate

Run script as (with python 3)

    python analyze_mechanics [input files]

or install it using the setup file, running it as

    analyze_mechanics [input files]

where the input files are nd2/npy files containing displacement data.

Åshild Telle / Simula Research Labratory / 2019

"""

import sys
import mpsmechanics as mc

if __name__ == "__main__":
     
    debug_mode, input_files = mc.get_input_files(sys.argv[1:])

    for f in input_files:
        if debug_mode:
            mc.analyze_mechanics(f)
        else:
            try:
                mc.analyze_mechanics(f)
            
            except Exception as e:
                print(f"Could not run analyze_mechanics; error msg: {e}")
                if f is not input_files[-1]:
                    print("Launching script for next file ...")

