#!/usr/bin/env python3

"""

Run script as

calculate_metrics *.nd2

"""

import sys
import mpsmechanics as mc

if __name__ == "__main__":
    debug_mode, input_files = mc.get_input_files(sys.argv[1:])

    for f in input_files:
        if debug_mode:
            mc.calculate_metrics(f)
        else:
            try:
                mc.calculate_metrics(f)
            
            except Exception as e:
                print(f"Could not run calculate_metrics; error msg: {e}")
                if f is not input_files[-1]:
                    print("Launching script for next file ...")


