#!/usr/bin/env python3

"""

Run script as

calculate_metrics *.nd2

"""

import sys
import os
import mpsmechanics as mc


from argparse import ArgumentParser


def cl_parser(args):

    parser = ArgumentParser()

    parser.add_argument("input_files", \
            help="BF files to run the script for", \
            nargs="+")

    parser.add_argument("-d", "--debug", \
            help="Run script in debug mode",
            action="store_true")

    args = parser.parse_args()

    input_files = mc.get_input_files(args.input_files)
    debug_mode = args.debug
    
    return input_files, debug_mode


if __name__ == "__main__":

    input_files, debug_mode = cl_parser(sys.argv[1:])

    assert os.path.isdir(sys.argv[1]), "Error: Give folder as first argument"
    output_folder = os.path.join(sys.argv[1], "metrics")

    mc.calculate_stats_chips(input_files, debug_mode, output_folder)

    print(f"Calculations finished, results saved in folder {ouput_folder}")
