#!/usr/bin/env python3

"""

Run script as

calculate_metrics *.nd2

"""

import sys
import os
import mpsmechanics as mc


from argparse import ArgumentParser


def cl_parser(args):

    parser = ArgumentParser()

    parser.add_argument("input_files", \
            help="BF files to run the script for", \
            nargs="+")

    parser.add_argument("-d", "--debug", \
            help="Run script in debug mode",
            action="store_true")

    parser.add_argument("-o", "--output", \
            help="Save output as/here; folder or csv file", \
            default= ".")

    args = parser.parse_args()

    input_files = mc.get_input_files(args.input_files)
    debug_mode = args.debug
    output = args.output

    assert (".csv" in output or os.path.isdir(output)), \
            "Give csv file or directory as output argument."

    if ".csv" in output:
        output_file = output
    else:
        output_file = os.path.join(output, "metrics_summary.csv")

    return input_files, debug_mode, output_file


if __name__ == "__main__":

    input_files, debug_mode, output_file = cl_parser(sys.argv[1:])
    mc.calculate_metrics_all(input_files, debug_mode, output_file)
