#!/usr/bin/env python3

"""

Run script as

calculate_metrics *.nd2

"""

import sys
import mpsmechanics as mc

if __name__ == "__main__":
    input_files = sys.argv[1:]

    for f in input_files:
        try:
            mc.calculate_metrics(f)
        except Exception as e:
            print("Could not run mechanical analysis; error ", e)
            print("Launching next data set ..")

