#!/usr/bin/env python3

"""

Tracks given points for a given data set over time.

Run as

    python calculate_stats_chips [displacement files] <layers> <sorting keys>

where displacement is a set of nd2/npy file with displacement data.
Pillar position files expected to be in a subfolder with the same
name as the displacement file (except from extention/suffix).

Åshild Telle / Simula Research Labratory / 2019

"""

import sys
import mpsmechanics as mc

if __name__ == "__main__":
    
    try:
        input_files = sys.argv[1:-2]
        layers = sys.argv[-2]
        sort_by =sys.argv[-1]
    except:
        print('Expected arguments: files, layers (one string), sort by (one string); ' + \
               'e.g. track_pillars */*/*.nd2 "track_pillars" "no_dose 1nM 10nM 100nM 1uM"')
        exit(-1)

    mc.calculate_stats_chips(input_files, layers, sort_by)
