#!/usr/bin/env python3

"""

Åshild Telle / Simula Research Labratory / 2019

"""

from argparse import ArgumentParser
import mpsmechanics as mc

def _cl_parser():
    parser = ArgumentParser()
    channel = "BF"

    mc.add_default_parser_arguments(parser, channel)
    keys = mc.add_parameters_parser_arguments(parser, 2)

    parser.add_argument(
        "-ms",
        "--motion_scaling_factor",
        default=1,
        help="Scaling factor for motion; 1 = original.",
        type=float,
    )
    keys.append(["motion_scaling_factor"])

    return parser, channel, keys

if __name__ == "__main__":
    mc.run_script(mc.track_pillars, \
            "Tracking pillars", *_cl_parser())
