#!/usr/bin/env python3

import sys
import mpsmechanics as mc

from argparse import ArgumentParser


def cl_parser(args):

    parser = ArgumentParser()

    parser.add_argument("input_files", \
            help="BF files to run the script for", \
            nargs="+")

    parser.add_argument("-d", "--debug", \
            help="Run script in debug mode",
            action="store_true")

    args = parser.parse_args()

    input_files = mc.get_input_files(args.input_files)
    debug_mode = args.debug

    return input_files, debug_mode

if __name__ == "__main__":
    input_files, debug_mode = cl_parser(sys.argv[1:])

    for f in input_files:
        if debug_mode:
            mc.track_motion(f)
        else:
            try:
                mc.track_motion(f)
            
            except Exception as e:
                print(f"Could not run track_motion; error msg: {e}")
                if f is not input_files[-1]:
                    print("Launching script for next file ...")


