#!/usr/bin/env python3

"""

Tracks given points for a given data set over time.

Run as

    python track_pillars [displacement files]

where displacement is a set of nd2/npy file with displacement data.
Pillar position files expected to be in a subfolder with the same
name as the displacement file (except from extention/suffix).

Åshild Telle / Simula Research Labratory / 2019

"""

import sys
import mpsmechanics as mc

if __name__ == "__main__":
    input_files = sys.argv[1:]

    for f in input_files:
        try:
            mc.track_pillars(f)
        except Exception as e:
            print("Could not run pillar tracking; error ", e)
            print("Launching next data set ..")
