#!/usr/bin/env python3

"""

Åshild Telle / Simula Research Labratory / 2019

"""

import numpy as np
import matplotlib as plt
import mps
import mpsmechanics as mc
import glob
import os
import sys
from argparse import ArgumentParser

def cl_parser(args):

    parser = ArgumentParser()
    channel = "BF"

    mc.add_default_parser_arguments(parser, channel)
    mc.add_animation_parser_arguments(parser, 0.2)
    mc.add_parameters_parser_arguments(parser)

    vargs = vars(parser.parse_args())
    input_files = mc.get_input_files(vargs.pop("input_files", None), channel)
    debug_mode = vargs.pop("debug_mode", None)

    return input_files, debug_mode, vargs


if __name__ == "__main__":

    input_files, debug_mode, config_options = cl_parser(sys.argv[1:])

    for input_file in input_files:
        if debug_mode:
            mc.visualize_mechanics(input_file, **config_options)
        else:
            try:
                mc.visualize_mechanics(input_file, **config_options)
            except Exception as e:
                print(f"Could not visualize mechanics; error msg: {e}")
                if input_files is not input_files[-1]:
                    print("Launching script for next file ...")
