#!/usr/bin/env python3

"""

Given data on displacement, this scripts finds the peak values and plots
spacial distribution of given metrics for these.

Run script as (with python 3)

    visualize_mechanics [input files]

where the input files are csv/nd2 files containing displacement data,
(see README).

Åshild Telle / Simula Research Labratory / 2019

"""

import sys
import mpsmechanics as mc

if __name__ == "__main__":

    try:
        input_files = sys.argv[1:-2]
        layers = sys.argv[-2]
        scale = float(sys.argv[-1])
    except:
        print('Expected arguments: files, layers (one string), scale for framerate (float); ' + \
               'e.g. visualize_vectorfield */*/*.nd2 analyze_mechanics 0.2')
        exit(-1)

    for f_in in input_files:
        try:
            mc.visualize_vectorfield(f_in, layers, scale)
        except Exception as e:
            print("Could not run visualization; error ", e)
            print("Launching next data set ..")
