#!/usr/bin/env python3

"""

Given data on displacement, this scripts finds the peak values and plots
spacial distribution of given metrics for these.

Run script as (with python 3)

    visualize_vectorfield [input files] [scaling nuber]

where the input files are csv/nd2 files containing displacement data,
(see README), scaling number change in frame rate.

Åshild Telle / Simula Research Labratory / 2019

"""

import sys
import mpsmechanics as mc

if __name__ == "__main__":
    scale = float(sys.argv[-1])
    debug_mode, input_files = mc.get_input_files(sys.argv[1:-1])

    for f in input_files:
        if debug_mode:
            mc.visualize_vectorfield(f, scale)
        else:
            try:
                mc.visualize_vectorfield(f, scale)
            
            except Exception as e:
                print(f"Could not run visualize_vectorfield; error msg: {e}")
                if f is not input_files[-1]:
                    print("Launching script for next file ...") 
