#!/usr/bin/env python3

"""

Åshild Telle / Simula Research Labratory / 2019

"""

from argparse import ArgumentParser
import mpsmechanics as mc

def _cl_parser():
    parser = ArgumentParser()
    channel = "Cyan"

    mc.add_default_parser_arguments(parser, channel)

    parser.add_argument(
        "-fl",
        "--fl_intervals",
        default=64,
        help="Subdivision of domain in x direction, for fluorescence plot.",
        type=int,
    )

    keys = [mc.add_animation_parser_arguments(parser) + ["fl_intervals"]]

    return parser, channel, keys

if __name__ == "__main__":
    mc.run_script(mc.visualize_fluorescence, \
            "visualization of corrected calcium", *_cl_parser())
