#!/usr/bin/env python3

"""

Given data on displacement, this scripts finds the peak values and plots
spacial distribution of given metrics for these.

Run script as (with python 3)

    visualize_mechanics [input files] [indices]

where the input files are csv/nd2 files containing displacement data,
(see README) and [indices] is a string which indicates which
properties should be recorded, e.g. given as "2 3 5". Quotation marks
required if more than one integer is given.

The id's correspond to the same metric for the analyze_mechanics.
Each id - except from 0, beat rate - has one or more corresponding
spacial plots.

For each of the remaning metrics (displacement, velocity,
principal strain, prevalence) we have
* For the metric itself: A quiver plot (arrows with magnitude),
  a direction plot (normalized arrows), a magnitude plot (heatmap).
* For each of x, y direction: A magnitude plot


The resulting plots are saved in
    the same folder as each input file ->
        subfolder with same identity as each input file ->
            "visualize_mechanics"

Åshild Telle / Simula Research Labratory / 2019

"""

import sys
import mpsmechanics as mc

if __name__ == "__main__":
    input_files, calc_properties, _ = mc.get_cl_input()
    mc.visualize_mechanics(input_files, calc_properties)
