#!/usr/bin/env python3

"""

Given data on displacement, this scripts finds the peak values and plots
spacial distribution of given metrics for these.

Run script as (with python 3)

    analyze_over_time [input files]

where the input files are csv/nd2 files containing displacement data,
(see README).

Åshild Telle / Simula Research Labratory / 2019

"""

import sys
import mpsmechanics as mc

if __name__ == "__main__":
    try:
        assert(len(sys.argv[1:])>1)
        input_files = sys.argv[1:]
        layers = "analyze_mechanics"
    except:
        print('Expected arguments: files, layers (one string); ' + \
               'e.g. visualize_over_time */*/*.nd2')
        exit(-1)

    for f_in in input_files:
        try:
            mc.visualize_over_time(f_in, layers)
        except Exception as e:
            print("Could not run visualization over time; error ", e)
            print("Launching next data set ..")
