#!/usr/bin/env python3

"""

Given data on displacement, this scripts finds the peak values and plots
spacial distribution of given metrics for these.

Run script as (with python 3)

    analyze_over_time [input files]

where the input files are csv/nd2 files containing displacement data,
(see README).

Åshild Telle / Simula Research Labratory / 2019

"""

import sys
import mpsmechanics as mc

if __name__ == "__main__":
    debug_mode, input_files = mc.get_input_files(sys.argv[1:])

    for f in input_files:
        if debug_mode:
            mc.visualize_over_time(f)
        else:
            try:
                mc.visualize_over_time(f)
            
            except Exception as e:
                print(f"Could not run visualize_over_time; error msg: {e}")
                if f is not input_files[-1]:
                    print("Launching script for next file ...") 
